package com.xyz.question_bank_management_system.modules.competency.service.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.xyz.question_bank_management_system.exception.BizException;
import com.xyz.question_bank_management_system.exception.ErrorCode;
import com.xyz.question_bank_management_system.modules.competency.dto.CareerMappingReviewRequest;
import com.xyz.question_bank_management_system.modules.competency.entity.*;
import com.xyz.question_bank_management_system.modules.competency.mapper.CareerMappingImportMapper;
import com.xyz.question_bank_management_system.modules.competency.mapper.OccupationSkillMapper;
import com.xyz.question_bank_management_system.modules.competency.mapper.SkillKnowledgeMapper;
import com.xyz.question_bank_management_system.modules.competency.service.CareerMappingImportService;
import com.xyz.question_bank_management_system.modules.competency.vo.CareerMappingImportVO;
import com.xyz.question_bank_management_system.util.HashUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service @RequiredArgsConstructor public class CareerMappingImportServiceImpl implements CareerMappingImportService {
 private static final List<String> HEADERS=List.of("occupation_label_en","occupation_label_zh","skill_relation","skill_title_en","skill_title_zh","course_name","knowledge_module","knowledge_point","onet_knowledge","onet_knowledge_importance","mapping_type","confidence","evidence");
 private final CareerMappingImportMapper mapper; private final OccupationSkillMapper occupationSkillMapper; private final SkillKnowledgeMapper skillKnowledgeMapper; private final ObjectMapper objectMapper;
 @Override @Transactional public CareerMappingImportVO importCsv(MultipartFile file,Long userId){
  if(file==null||file.isEmpty())throw BizException.of(ErrorCode.PARAM_ERROR,"CSV file is required");
  try{String csv=new String(file.getBytes(),StandardCharsets.UTF_8);List<List<String>> records=parse(csv);if(records.isEmpty()||!HEADERS.equals(records.get(0)))throw BizException.of(ErrorCode.PARAM_ERROR,"CSV header does not match the 13-column mapping contract");
   CareerMappingImportBatch batch=new CareerMappingImportBatch();batch.setBatchCode(code());batch.setFileName(Optional.ofNullable(file.getOriginalFilename()).orElse("career-mapping.csv"));batch.setFileHash(HashUtil.sha256(csv));batch.setStatus("IMPORTED");batch.setCreatedBy(userId);batch.setRowCount(Math.max(0,records.size()-1));int candidate=0,unresolved=0,out=0;List<CareerMappingImportRow> rows=new ArrayList<>();
   for(int index=1;index<records.size();index++){List<String> c=records.get(index);if(c.size()!=13)throw BizException.of(ErrorCode.PARAM_ERROR,"invalid column count at row "+(index+1));CareerMappingImportRow row=row(c,index+1);match(row);if("CANDIDATE".equals(row.getMatchStatus()))candidate++;else if("OUT_OF_CATALOG".equals(row.getMatchStatus()))out++;else unresolved++;rows.add(row);}
   batch.setCandidateCount(candidate);batch.setUnresolvedCount(unresolved);batch.setOutOfCatalogCount(out);mapper.insertBatch(batch);for(CareerMappingImportRow row:rows){row.setBatchId(batch.getId());mapper.insertRow(row);}return vo(batch);
  }catch(BizException e){throw e;}catch(Exception e){throw BizException.of(ErrorCode.PARAM_ERROR,"unable to read CSV: "+e.getMessage());}}
 @Override public List<CareerMappingImportBatch> batches(int limit){return mapper.batches(Math.max(1,Math.min(100,limit)));}
 @Override public List<CareerMappingImportRow> rows(String batchCode,String status,int limit){CareerMappingImportBatch b=mapper.batch(batchCode);if(b==null)throw BizException.of(ErrorCode.NOT_FOUND,"mapping batch not found");return mapper.rows(b.getId(),blank(status),Math.max(1,Math.min(1000,limit)));}
 @Override public Map<String,Object> summary(String batchCode){CareerMappingImportBatch b=mapper.batch(batchCode);if(b==null)throw BizException.of(ErrorCode.NOT_FOUND,"mapping batch not found");return Map.of("batchCode",batchCode,"batchStatus",b.getStatus(),"rowCount",b.getRowCount(),"statusCounts",mapper.statusSummary(b.getId()));}
 @Override @Transactional public void review(Long rowId,CareerMappingReviewRequest request,Long userId){CareerMappingImportRow old=mapper.row(rowId);if(old==null)throw BizException.of(ErrorCode.NOT_FOUND,"mapping row not found");String decision=defaultText(request.getDecision(),"APPROVED");mapper.review(rowId,request.getOccupationId(),request.getSkillId(),request.getCourseId(),request.getModuleExternalId(),request.getKnowledgePointId(),decision,request.getReason(),userId);mapper.decision(rowId,decision,json(old),json(request),request.getReason(),userId);}
 @Override @Transactional public CareerMappingImportVO publish(String batchCode,Long userId){CareerMappingImportBatch batch=mapper.batch(batchCode);if(batch==null)throw BizException.of(ErrorCode.NOT_FOUND,"mapping batch not found");List<CareerMappingImportRow> rows=mapper.approvedRows(batch.getId());if(rows.isEmpty())throw BizException.of(ErrorCode.CONFLICT,"no APPROVED mapping rows to publish");try{for(CareerMappingImportRow row:rows){if(row.getOccupationId()==null||row.getSkillId()==null||row.getCourseId()==null||row.getKnowledgePointId()==null)throw BizException.of(ErrorCode.CONFLICT,"approved row has incomplete target ids: "+row.getRowNo());if(mapper.activePointInActiveCourse(row.getCourseId(),row.getKnowledgePointId())!=1)throw BizException.of(ErrorCode.CONFLICT,"approved row does not point to ACTIVE course graph: "+row.getRowNo());String occupationType="optional".equalsIgnoreCase(row.getSkillRelation())?"optional":"essential";OccupationSkill os=occupationSkillMapper.selectByBusinessKey(row.getOccupationId(),row.getSkillId(),occupationType);if(os==null){os=new OccupationSkill();os.setOccupationId(row.getOccupationId());os.setSkillId(row.getSkillId());os.setRequirementType(occupationType);os.setImportanceScore(BigDecimal.ONE);os.setRequiredLevel(null);os.setSourceRef("career_mapping:"+batchCode+":"+row.getRowNo());occupationSkillMapper.insert(os);}String requirement="DIRECT".equals(row.getNormalizedMappingType())?"core":"support";SkillKnowledge sk=skillKnowledgeMapper.selectByBusinessKey(row.getSkillId(),row.getKnowledgePointId(),requirement);if(sk==null){sk=new SkillKnowledge();sk.setSkillId(row.getSkillId());sk.setKnowledgePointId(row.getKnowledgePointId());sk.setRequirementType(requirement);sk.setWeight(BigDecimal.ONE);sk.setConfidence(row.getConfidence()==null?new BigDecimal("0.8000"):row.getConfidence());sk.setSourceType("CSV_REVIEWED");sk.setSourceRef(batchCode);sk.setEvidenceText(row.getEvidence());skillKnowledgeMapper.insert(sk);}else{sk.setWeight(BigDecimal.ONE);sk.setConfidence(row.getConfidence()==null?sk.getConfidence():row.getConfidence());sk.setSourceType("CSV_REVIEWED");sk.setSourceRef(batchCode);sk.setEvidenceText(row.getEvidence());skillKnowledgeMapper.update(sk);}}mapper.updateBatchStatus(batch.getId(),"PUBLISHED",null);batch.setStatus("PUBLISHED");return vo(batch);}catch(RuntimeException ex){mapper.updateBatchStatus(batch.getId(),"PUBLISH_FAILED",ex.getMessage());throw ex;}}
 private CareerMappingImportRow row(List<String> c,int rowNo){CareerMappingImportRow r=new CareerMappingImportRow();r.setRowNo(rowNo);r.setOccupationLabelEn(c.get(0));r.setOccupationLabelZh(c.get(1));r.setSkillRelation(c.get(2));r.setSkillTitleEn(c.get(3));r.setSkillTitleZh(c.get(4));r.setCourseName(c.get(5));r.setKnowledgeModule(c.get(6));r.setKnowledgePoint(c.get(7));r.setOnetKnowledge(c.get(8));r.setOnetKnowledgeImportance(c.get(9));r.setMappingType(c.get(10));r.setConfidence(decimal(c.get(11)));r.setEvidence(c.get(12));r.setNormalizedMappingType(Map.of("直接","DIRECT","辅助","SUPPORT","迁移","TRANSFER","先修","PREREQUISITE").getOrDefault(c.get(10),"UNKNOWN"));return r;}
 private void match(CareerMappingImportRow r){r.setOccupationId(mapper.occupationId(r.getOccupationLabelZh()));r.setSkillId(mapper.skillId(r.getSkillTitleZh()));if("课程外知识".equals(r.getCourseName())){r.setMatchStatus("OUT_OF_CATALOG");r.setMatchReason("course is outside current catalog");return;}r.setCourseId(mapper.courseId(r.getCourseName()));if(r.getCourseId()==null){r.setMatchStatus("COURSE_MISSING");r.setMatchReason("course not found");return;}r.setKnowledgePointId(mapper.pointId(r.getCourseId(),r.getKnowledgePoint()));if(r.getKnowledgePointId()==null){r.setMatchStatus("GRAPH_MISSING");r.setMatchReason("knowledge point not found by exact name");return;}r.setMatchStatus("CANDIDATE");r.setMatchReason(r.getOccupationId()==null||r.getSkillId()==null?"course point matched; occupation or skill requires review":"all entities exactly matched; requires reviewer signoff");}
 private List<List<String>> parse(String csv){List<List<String>> rows=new ArrayList<>();List<String> row=new ArrayList<>();StringBuilder cell=new StringBuilder();boolean quoted=false;for(int i=0;i<csv.length();i++){char ch=csv.charAt(i);if(ch=='"'){if(quoted&&i+1<csv.length()&&csv.charAt(i+1)=='"'){cell.append('"');i++;}else quoted=!quoted;}else if(ch==','&&!quoted){row.add(cell.toString());cell.setLength(0);}else if((ch=='\n'||ch=='\r')&&!quoted){if(ch=='\r'&&i+1<csv.length()&&csv.charAt(i+1)=='\n')i++;row.add(cell.toString());cell.setLength(0);if(!(row.size()==1&&row.get(0).isBlank()))rows.add(row);row=new ArrayList<>();}else cell.append(ch);}if(quoted)throw BizException.of(ErrorCode.PARAM_ERROR,"unterminated CSV quote");if(cell.length()>0||!row.isEmpty()){row.add(cell.toString());rows.add(row);}if(!rows.isEmpty()&&!rows.get(0).isEmpty())rows.get(0).set(0,rows.get(0).get(0).replace("\uFEFF",""));return rows;}
 private CareerMappingImportVO vo(CareerMappingImportBatch b){CareerMappingImportVO v=new CareerMappingImportVO();v.setBatchCode(b.getBatchCode());v.setRowCount(b.getRowCount());v.setCandidateCount(b.getCandidateCount());v.setUnresolvedCount(b.getUnresolvedCount());v.setOutOfCatalogCount(b.getOutOfCatalogCount());v.setStatus(b.getStatus());return v;} private String code(){return "CMI-"+java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS"));} private BigDecimal decimal(String v){try{return new BigDecimal(v);}catch(Exception e){return null;}} private String blank(String v){return v==null||v.isBlank()?null:v.trim();}private String defaultText(String v,String d){String x=blank(v);return x==null?d:x;}private String json(Object x){try{return objectMapper.writeValueAsString(x);}catch(Exception e){return "{}";}}
}
