package com.xyz.question_bank_management_system.modules.competency.service.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.xyz.question_bank_management_system.common.PageResponse;
import com.xyz.question_bank_management_system.exception.BizException;
import com.xyz.question_bank_management_system.exception.ErrorCode;
import com.xyz.question_bank_management_system.modules.competency.dto.*;
import com.xyz.question_bank_management_system.modules.competency.dto.CompetencyImportValidateRequest.*;
import com.xyz.question_bank_management_system.modules.competency.entity.*;
import com.xyz.question_bank_management_system.modules.competency.mapper.*;
import com.xyz.question_bank_management_system.modules.competency.service.*;
import com.xyz.question_bank_management_system.modules.competency.vo.*;
import com.xyz.question_bank_management_system.modules.knowledge.mapper.KnowledgePointMapper;
import com.xyz.question_bank_management_system.util.HashUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.math.BigDecimal;
import java.util.*;

@Service
@RequiredArgsConstructor
public class CompetencyImportServiceImpl implements CompetencyImportService {
    private final ObjectMapper objectMapper; private final OccupationMapper occupationMapper; private final SkillMapper skillMapper; private final KnowledgePointMapper pointMapper; private final DataSyncRecordMapper recordMapper; private final DataSyncRecordService recordService; private final CompetencyImportWriter writer;
    @Override public ImportValidationVO validate(CompetencyImportValidateRequest request) { ImportValidationVO result=new ImportValidationVO(); normalizeCollections(request); result.setFetchedCount(total(request)); validateRequired(request,result); validateDuplicates(request,result); validateValues(request,result); validateReferences(request,result); result.setFailedCount((int)result.getItems().stream().filter(i->"failed".equals(i.getAction())).count()); result.setValid(result.getFailedCount()==0); result.setValidationHash(hash(request)); if(result.isValid()) previewActions(request,result); return result; }
    @Override public ImportValidationVO commit(CompetencyImportCommitRequest request, Long operatorId) { ImportValidationVO validation=validate(request); if(!Objects.equals(validation.getValidationHash(),request.getValidationHash())) throw BizException.of(ErrorCode.CONFLICT,"Import content differs from validation result"); int fetched=validation.getFetchedCount(); Long recordId=recordService.start(request.getSourceName(),request.getSyncVersion(),operatorId,fetched); if(!validation.isValid()){recordService.finishFailure(recordId,fetched,validation.getFailedCount(),"Import validation failed");throw BizException.of(ErrorCode.PARAM_ERROR,"Import validation failed");} try { CompetencyImportWriter.Counts counts=writer.write(request); validation.setInsertedCount(counts.inserted);validation.setUpdatedCount(counts.updated);recordService.finishSuccess(recordId,fetched,counts.inserted,counts.updated);return validation; } catch(RuntimeException ex){recordService.finishFailure(recordId,fetched,1,ex.getMessage());throw ex;} }
    @Override public PageResponse<DataSyncRecordVO> records(Integer page,Integer size){int safePage=page==null?1:Math.max(1,page);int safeSize=size==null?20:Math.min(100,Math.max(1,size));List<DataSyncRecordVO> list=recordMapper.selectPage((long)(safePage-1)*safeSize,safeSize).stream().map(this::toVo).toList();return PageResponse.of(safePage,safeSize,recordMapper.countPage(),list);}
    @Override public DataSyncRecordVO record(Long id){DataSyncRecord record=recordMapper.selectById(id);if(record==null)throw BizException.of(ErrorCode.NOT_FOUND,"Import record not found");return toVo(record);}
    private void validateRequired(CompetencyImportValidateRequest r,ImportValidationVO v){if(blank(r.getSourceName())==null)add(v,"request","sourceName","failed","sourceName is required");if(blank(r.getSyncVersion())==null)add(v,"request","syncVersion","failed","syncVersion is required");for(OccupationInput i:r.getOccupations())if(blank(i.getSourceRef())==null||blank(i.getNameZh())==null)add(v,"occupation",String.valueOf(i.getSourceRef()),"failed","sourceRef and nameZh are required");for(SkillInput i:r.getSkills())if(blank(i.getSourceRef())==null||blank(i.getNameZh())==null)add(v,"skill",String.valueOf(i.getSourceRef()),"failed","sourceRef and nameZh are required");for(KnowledgePointInput i:r.getKnowledgePoints())if(blank(i.getCode())==null||blank(i.getName())==null)add(v,"knowledge_point",String.valueOf(i.getCode()),"failed","code and name are required");}
    private void validateDuplicates(CompetencyImportValidateRequest r,ImportValidationVO v){duplicates(r.getOccupations().stream().map(OccupationInput::getSourceRef).toList(),"occupation",v);duplicates(r.getSkills().stream().map(SkillInput::getSourceRef).toList(),"skill",v);duplicates(r.getKnowledgePoints().stream().map(KnowledgePointInput::getCode).toList(),"knowledge_point",v);}
    private void duplicates(List<String> keys,String type,ImportValidationVO v){Set<String> seen=new HashSet<>();for(String key:keys)if(key!=null&&!seen.add(key))add(v,type,key,"failed","duplicate business key in request");}
    private void validateValues(CompetencyImportValidateRequest r,ImportValidationVO v){for(OccupationSkillInput i:r.getOccupationSkills()){range(i.getImportanceScore(),"occupation_skill",i.getOccupationSourceRef(),v);range(i.getRequiredLevel(),"occupation_skill",i.getOccupationSourceRef(),v);}for(SkillKnowledgeInput i:r.getSkillKnowledge()){range(i.getWeight(),"skill_knowledge",i.getKnowledgeCode(),v);range(i.getConfidence(),"skill_knowledge",i.getKnowledgeCode(),v);}for(KnowledgeRelationInput i:r.getKnowledgeRelations()){range(i.getWeight(),"knowledge_relation",i.getSourceCode(),v);range(i.getConfidence(),"knowledge_relation",i.getSourceCode(),v);if(Objects.equals(i.getSourceCode(),i.getTargetCode()))add(v,"knowledge_relation",String.valueOf(i.getSourceCode()),"failed","source and target must differ");}for(KnowledgePointInput i:r.getKnowledgePoints())if(i.getDifficulty()!=null&&(i.getDifficulty()<1||i.getDifficulty()>5))add(v,"knowledge_point",i.getCode(),"failed","difficulty must be 1..5");}
    private void validateReferences(CompetencyImportValidateRequest r,ImportValidationVO v){Set<String> occupationRefs=new HashSet<>(r.getOccupations().stream().map(OccupationInput::getSourceRef).toList());Set<String> skillRefs=new HashSet<>(r.getSkills().stream().map(SkillInput::getSourceRef).toList());Set<String> codes=new HashSet<>(r.getKnowledgePoints().stream().map(KnowledgePointInput::getCode).toList());for(OccupationAliasInput i:r.getOccupationAliases())if(!occupationRefs.contains(i.getOccupationSourceRef())&&occupationMapper.selectBySource(r.getSourceName(),i.getOccupationSourceRef())==null)add(v,"occupation_alias",String.valueOf(i.getOccupationSourceRef()),"failed","occupation reference not found");for(OccupationSkillInput i:r.getOccupationSkills()){if(!occupationRefs.contains(i.getOccupationSourceRef())&&occupationMapper.selectBySource(r.getSourceName(),i.getOccupationSourceRef())==null)add(v,"occupation_skill",String.valueOf(i.getOccupationSourceRef()),"failed","occupation reference not found");if(!skillRefs.contains(i.getSkillSourceRef())&&skillMapper.selectBySource(r.getSourceName(),i.getSkillSourceRef())==null)add(v,"occupation_skill",String.valueOf(i.getSkillSourceRef()),"failed","skill reference not found");}for(KnowledgePointInput i:r.getKnowledgePoints())if(blank(i.getParentCode())!=null&&!codes.contains(i.getParentCode())&&pointMapper.selectByCode(i.getParentCode())==null)add(v,"knowledge_point",i.getCode(),"failed","parentCode not found");for(SkillKnowledgeInput i:r.getSkillKnowledge())if(!skillRefs.contains(i.getSkillSourceRef())||(!codes.contains(i.getKnowledgeCode())&&pointMapper.selectByCode(i.getKnowledgeCode())==null))add(v,"skill_knowledge",String.valueOf(i.getSkillSourceRef()),"failed","skill or knowledge reference not found");for(KnowledgeRelationInput i:r.getKnowledgeRelations())if((!codes.contains(i.getSourceCode())&&pointMapper.selectByCode(i.getSourceCode())==null)||(!codes.contains(i.getTargetCode())&&pointMapper.selectByCode(i.getTargetCode())==null))add(v,"knowledge_relation",String.valueOf(i.getSourceCode()),"failed","knowledge reference not found");}
    private void previewActions(CompetencyImportValidateRequest r,ImportValidationVO v){for(OccupationInput i:r.getOccupations())add(v,"occupation",i.getSourceRef(),occupationMapper.selectBySource(r.getSourceName(),i.getSourceRef())==null?"insert":"update",null);for(SkillInput i:r.getSkills())add(v,"skill",i.getSourceRef(),skillMapper.selectBySource(r.getSourceName(),i.getSourceRef())==null?"insert":"update",null);for(KnowledgePointInput i:r.getKnowledgePoints())add(v,"knowledge_point",i.getCode(),pointMapper.selectByCode(i.getCode())==null?"insert":"update",null);}
    private String hash(CompetencyImportValidateRequest r){
        try {
            @SuppressWarnings("unchecked") Map<String,Object> payload = objectMapper.convertValue(r, Map.class);
            payload.remove("validationHash");
            return HashUtil.sha256(objectMapper.writeValueAsString(payload));
        } catch(Exception e){throw new IllegalStateException("Unable to hash import request",e);}
    }
    private void normalizeCollections(CompetencyImportValidateRequest r){if(r.getOccupations()==null)r.setOccupations(new ArrayList<>());if(r.getOccupationAliases()==null)r.setOccupationAliases(new ArrayList<>());if(r.getSkills()==null)r.setSkills(new ArrayList<>());if(r.getOccupationSkills()==null)r.setOccupationSkills(new ArrayList<>());if(r.getKnowledgePoints()==null)r.setKnowledgePoints(new ArrayList<>());if(r.getSkillKnowledge()==null)r.setSkillKnowledge(new ArrayList<>());if(r.getKnowledgeRelations()==null)r.setKnowledgeRelations(new ArrayList<>());}
    private int total(CompetencyImportValidateRequest r){return r.getOccupations().size()+r.getOccupationAliases().size()+r.getSkills().size()+r.getOccupationSkills().size()+r.getKnowledgePoints().size()+r.getSkillKnowledge().size()+r.getKnowledgeRelations().size();} private void range(BigDecimal value,String type,String key,ImportValidationVO v){if(value!=null&&(value.compareTo(BigDecimal.ZERO)<0||value.compareTo(BigDecimal.ONE)>0))add(v,type,String.valueOf(key),"failed","value must be between 0 and 1");} private String blank(String value){return value==null||value.isBlank()?null:value.trim();} private void add(ImportValidationVO v,String type,String key,String action,String message){v.getItems().add(new ImportValidationVO.Item(type,key,action,message));}
    private DataSyncRecordVO toVo(DataSyncRecord r){DataSyncRecordVO v=new DataSyncRecordVO();v.setId(r.getId());v.setSyncType(r.getSyncType());v.setSourceName(r.getSourceName());v.setTriggerType(r.getTriggerType());v.setTriggerBy(r.getTriggerBy());v.setSyncVersion(r.getSyncVersion());v.setStatus(r.getStatus());v.setFetchedCount(r.getFetchedCount());v.setInsertedCount(r.getInsertedCount());v.setUpdatedCount(r.getUpdatedCount());v.setFailedCount(r.getFailedCount());v.setErrorMessage(r.getErrorMessage());v.setStartedAt(r.getStartedAt());v.setFinishedAt(r.getFinishedAt());v.setCreatedAt(r.getCreatedAt());return v;}
}
