CREATE TABLE IF NOT EXISTS learning_path_version(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,path_id BIGINT UNSIGNED NOT NULL,version BIGINT UNSIGNED NOT NULL,path_mode VARCHAR(32) NOT NULL,based_on_profile_version BIGINT UNSIGNED NOT NULL,graph_version VARCHAR(64) NOT NULL,policy_version VARCHAR(64) NOT NULL,model_version VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL,change_reason VARCHAR(64) NULL,correlation_id VARCHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_path_version(path_id,version),KEY idx_path_active(path_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS learning_path_progress(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,path_id BIGINT UNSIGNED NOT NULL,last_processed_interaction_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,last_processed_interaction_id BIGINT UNSIGNED NULL,consecutive_wrong_count INT NOT NULL DEFAULT 0,window_attempt_count INT NOT NULL DEFAULT 0,window_mastery_start DECIMAL(6,4) NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_path_progress(path_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS path_update_log(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,path_id BIGINT UNSIGNED NOT NULL,old_version BIGINT UNSIGNED NULL,new_version BIGINT UNSIGNED NOT NULL,trigger_event_types_json JSON NOT NULL,trigger_interaction_ids_json JSON NOT NULL,affected_knowledge_point_ids_json JSON NOT NULL,added_step_ids_json JSON NOT NULL,removed_step_ids_json JSON NOT NULL,retained_step_ids_json JSON NOT NULL,correlation_id VARCHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),KEY idx_path_update(path_id,new_version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS path_policy(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,policy_version VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL,mastery_threshold DECIMAL(6,4) NOT NULL,confidence_threshold DECIMAL(6,4) NOT NULL,max_path_length INT NOT NULL,max_neighbor_hops INT NOT NULL,config_json JSON NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_path_policy(policy_version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP PROCEDURE IF EXISTS stage10_add_column;
DELIMITER $$
CREATE PROCEDURE stage10_add_column(IN t VARCHAR(64),IN c VARCHAR(64),IN d TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=t AND column_name=c) THEN SET @x=d;PREPARE s FROM @x;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL stage10_add_column('learning_path','path_code','ALTER TABLE learning_path ADD COLUMN path_code VARCHAR(64) NULL');
CALL stage10_add_column('learning_path','target_knowledge_point_id','ALTER TABLE learning_path ADD COLUMN target_knowledge_point_id BIGINT UNSIGNED NULL');
CALL stage10_add_column('learning_path','current_version','ALTER TABLE learning_path ADD COLUMN current_version BIGINT UNSIGNED NULL');
CALL stage10_add_column('learning_path','idempotency_key','ALTER TABLE learning_path ADD COLUMN idempotency_key VARCHAR(128) NULL');
CALL stage10_add_column('learning_path_item','path_version_id','ALTER TABLE learning_path_item ADD COLUMN path_version_id BIGINT UNSIGNED NULL');
CALL stage10_add_column('learning_path_item','path_step_code','ALTER TABLE learning_path_item ADD COLUMN path_step_code VARCHAR(64) NULL');
CALL stage10_add_column('learning_path_item','stage','ALTER TABLE learning_path_item ADD COLUMN stage VARCHAR(24) NULL');
CALL stage10_add_column('learning_path_item','reason_code','ALTER TABLE learning_path_item ADD COLUMN reason_code VARCHAR(64) NULL');
CALL stage10_add_column('learning_path_item','mastery_before','ALTER TABLE learning_path_item ADD COLUMN mastery_before DECIMAL(6,4) NULL');
CALL stage10_add_column('learning_path_item','confidence_before','ALTER TABLE learning_path_item ADD COLUMN confidence_before DECIMAL(6,4) NULL');
CALL stage10_add_column('learning_path_item','completed_at','ALTER TABLE learning_path_item ADD COLUMN completed_at DATETIME(3) NULL');
DROP PROCEDURE stage10_add_column;
