package com.xyz.question_bank_management_system.modules.course.mapper;
import com.xyz.question_bank_management_system.modules.course.entity.ExamEligibilitySnapshot;import org.apache.ibatis.annotations.*;import java.util.*;
@Mapper public interface LearningOutcomeMapper {
 @Select("SELECT COUNT(*) FROM course_knowledge ck JOIN knowledge_point k ON k.id=ck.knowledge_point_id WHERE ck.course_id=#{courseId} AND k.status='ACTIVE' AND k.is_deleted=0 AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(k.metadata_json,'$.pathEligible')),'true')='true'") int totalKnowledge(Long courseId);
 @Select("SELECT COUNT(*) FROM student_knowledge_state s JOIN course_knowledge ck ON ck.knowledge_point_id=s.knowledge_point_id AND ck.course_id=s.course_id JOIN knowledge_point k ON k.id=s.knowledge_point_id WHERE s.user_id=#{userId} AND s.course_id=#{courseId} AND k.status='ACTIVE' AND k.is_deleted=0 AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(k.metadata_json,'$.pathEligible')),'true')='true' AND s.mastery_value>=#{mastery} AND s.confidence>=#{confidence}") int completedKnowledge(@Param("userId")Long userId,@Param("courseId")Long courseId,@Param("mastery")java.math.BigDecimal mastery,@Param("confidence")java.math.BigDecimal confidence);
 @Select("SELECT course_id,required FROM training_goal_course_requirement WHERE goal_id=#{goalId} ORDER BY course_id") List<Map<String,Object>> requirements(Long goalId);
 @Insert("INSERT INTO exam_eligibility_snapshot(snapshot_code,user_id,goal_id,eligible,course_versions_json,profile_versions_json,rule_version,result_json,correlation_id,calculated_at,created_at) VALUES(#{snapshotCode},#{userId},#{goalId},#{eligible},#{courseVersionsJson},#{profileVersionsJson},#{ruleVersion},#{resultJson},#{correlationId},#{calculatedAt},NOW(3))") @Options(useGeneratedKeys=true,keyProperty="id") int insertEligibility(ExamEligibilitySnapshot v);
 @Select("SELECT l.* FROM knowledge_state_update_log l WHERE l.user_id=#{userId} AND l.course_id=#{courseId} ORDER BY l.id DESC LIMIT 100") List<Map<String,Object>> masteryHistory(@Param("userId")Long userId,@Param("courseId")Long courseId);
 @Select("SELECT u.* FROM path_update_log u JOIN learning_path p ON p.id=u.path_id WHERE p.user_id=#{userId} AND p.course_id=#{courseId} ORDER BY u.id DESC LIMIT 50") List<Map<String,Object>> pathHistory(@Param("userId")Long userId,@Param("courseId")Long courseId);
 @Select("SELECT * FROM resource_action_decision WHERE user_id=#{userId} AND course_id=#{courseId} ORDER BY id DESC LIMIT 50") List<Map<String,Object>> resourceActions(@Param("userId")Long userId,@Param("courseId")Long courseId);
}
