-- Stage 06 schema. Re-runnable; execute manually only.
USE question_bank;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='model_config')=0,
'CREATE TABLE model_config (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,owner_type VARCHAR(24) NOT NULL DEFAULT ''system'',owner_id BIGINT UNSIGNED NULL,provider_key VARCHAR(100) NOT NULL,label VARCHAR(128) NOT NULL,provider_type VARCHAR(32) NOT NULL DEFAULT ''API'',base_url VARCHAR(500) NOT NULL,api_key_cipher TEXT NULL,model VARCHAR(128) NOT NULL,temperature DOUBLE NULL,enabled TINYINT NOT NULL DEFAULT 1,is_default TINYINT NOT NULL DEFAULT 0,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_model_config_owner_key(owner_type,owner_id,provider_key),KEY idx_model_config_owner_enabled(owner_type,owner_id,enabled,is_default)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''model_config exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='prompt_template')=0,
'CREATE TABLE prompt_template (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,owner_type VARCHAR(24) NOT NULL DEFAULT ''system'',owner_id BIGINT UNSIGNED NULL,template_name VARCHAR(128) NOT NULL,task_type VARCHAR(64) NOT NULL,description VARCHAR(1000) NULL,prompt_text LONGTEXT NOT NULL,version VARCHAR(64) NOT NULL DEFAULT ''v1'',created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_prompt_template_owner_version(owner_type,owner_id,template_name,task_type,version),KEY idx_prompt_template_owner_task(owner_type,owner_id,task_type,updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''prompt_template exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='agent_definition')=0,
'CREATE TABLE agent_definition (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,agent_code VARCHAR(64) NOT NULL,agent_name VARCHAR(128) NOT NULL,role_type VARCHAR(32) NOT NULL,description VARCHAR(1000) NULL,default_model_config_id BIGINT UNSIGNED NULL,prompt_template_id BIGINT UNSIGNED NULL,config_json LONGTEXT NULL,status TINYINT NOT NULL DEFAULT 1,version VARCHAR(64) NOT NULL DEFAULT ''v1'',created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_agent_definition_code_version(agent_code,version),KEY idx_agent_definition_enabled(agent_code,status,updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''agent_definition exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='agent_task')=0,
'CREATE TABLE agent_task (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,task_code VARCHAR(64) NULL,task_type VARCHAR(40) NOT NULL,user_id BIGINT UNSIGNED NULL,teacher_id BIGINT UNSIGNED NULL,target_type VARCHAR(24) NULL,target_id BIGINT UNSIGNED NULL,input_json LONGTEXT NULL,status VARCHAR(24) NOT NULL DEFAULT ''queued'',current_step_no INT NOT NULL DEFAULT 0,result_summary LONGTEXT NULL,error_message VARCHAR(2000) NULL,started_at DATETIME(3) NULL,finished_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_agent_task_code(task_code),KEY idx_agent_task_status_created(status,created_at),KEY idx_agent_task_teacher_created(teacher_id,created_at),KEY idx_agent_task_user_created(user_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''agent_task exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='agent_step')=0,
'CREATE TABLE agent_step (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,agent_task_id BIGINT UNSIGNED NOT NULL,step_no INT NOT NULL,agent_definition_id BIGINT UNSIGNED NULL,step_type VARCHAR(40) NOT NULL,input_json LONGTEXT NULL,output_json LONGTEXT NULL,llm_call_id BIGINT UNSIGNED NULL,status VARCHAR(24) NOT NULL DEFAULT ''pending'',latency_ms INT NULL,started_at DATETIME(3) NULL,finished_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_agent_step_task_no(agent_task_id,step_no),KEY idx_agent_step_call(llm_call_id),KEY idx_agent_step_status(status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''agent_step exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='agent_review')=0,
'CREATE TABLE agent_review (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,agent_task_id BIGINT UNSIGNED NOT NULL,agent_step_id BIGINT UNSIGNED NULL,target_type VARCHAR(24) NOT NULL,target_id BIGINT UNSIGNED NULL,factual_score DECIMAL(6,4) NULL,coverage_score DECIMAL(6,4) NULL,difficulty_match_score DECIMAL(6,4) NULL,hallucination_rate DECIMAL(6,4) NULL,source_consistency_score DECIMAL(6,4) NULL,review_status VARCHAR(24) NOT NULL DEFAULT ''pending'',review_report LONGTEXT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),KEY idx_agent_review_task(agent_task_id,created_at),KEY idx_agent_review_step(agent_step_id),KEY idx_agent_review_status(review_status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''agent_review exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='agent_decision')=0,
'CREATE TABLE agent_decision (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,agent_task_id BIGINT UNSIGNED NOT NULL,agent_step_id BIGINT UNSIGNED NULL,decision_type VARCHAR(40) NOT NULL,target_type VARCHAR(24) NULL,target_id BIGINT UNSIGNED NULL,decision_value VARCHAR(255) NULL,decision_reason LONGTEXT NULL,confidence DECIMAL(6,4) NULL,evidence_json LONGTEXT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),KEY idx_agent_decision_task(agent_task_id,created_at),KEY idx_agent_decision_step(agent_step_id),KEY idx_agent_decision_type(decision_type,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci', 'SELECT ''agent_decision exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

-- qb_llm_call is retained, but its business type is standardized to a descriptive code.
SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='qb_llm_call' AND column_name='biz_type' AND column_type NOT LIKE 'varchar%')=1,
'ALTER TABLE qb_llm_call MODIFY COLUMN biz_type VARCHAR(40) NOT NULL', 'SELECT ''qb_llm_call.biz_type already standardized''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;

SET @stage06_sql := IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='qb_llm_call' AND index_name='idx_qb_llm_call_biz')=0,
'CREATE INDEX idx_qb_llm_call_biz ON qb_llm_call(biz_type,biz_id,created_at)', 'SELECT ''idx_qb_llm_call_biz exists''');
PREPARE stage06_stmt FROM @stage06_sql; EXECUTE stage06_stmt; DEALLOCATE PREPARE stage06_stmt;
