-- Stage 08 additive schema. Run only after the precheck is clean.
CREATE TABLE IF NOT EXISTS course_chapter(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,course_id BIGINT UNSIGNED NOT NULL,chapter_code VARCHAR(64) NOT NULL,chapter_name VARCHAR(255) NOT NULL,order_no INT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_course_chapter_code(course_id,chapter_code),KEY idx_course_chapter_order(course_id,order_no),CONSTRAINT fk_course_chapter_course FOREIGN KEY(course_id) REFERENCES course(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS knowledge_graph_version(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,version_code VARCHAR(64) NOT NULL,course_id BIGINT UNSIGNED NOT NULL,description VARCHAR(500) NULL,status VARCHAR(24) NOT NULL,node_count INT NOT NULL DEFAULT 0,edge_count INT NOT NULL DEFAULT 0,content_hash CHAR(64) NULL,validation_report_json JSON NULL,correlation_id VARCHAR(64) NULL,created_by BIGINT UNSIGNED NULL,activated_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_graph_version_code(version_code),KEY idx_graph_version_course_status(course_id,status),CONSTRAINT fk_graph_version_course FOREIGN KEY(course_id) REFERENCES course(id) ON DELETE RESTRICT,CONSTRAINT ck_graph_version_status CHECK(status IN('DRAFT','VALIDATING','ACTIVE','REJECTED','ARCHIVED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS knowledge_graph_sync_record(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,graph_version_id BIGINT UNSIGNED NOT NULL,sync_code VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL,node_count INT NULL,edge_count INT NULL,content_hash CHAR(64) NULL,error_message VARCHAR(1000) NULL,correlation_id VARCHAR(64) NULL,started_at DATETIME(3) NULL,finished_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_graph_sync_code(sync_code),KEY idx_graph_sync_version(graph_version_id,created_at),CONSTRAINT fk_graph_sync_version FOREIGN KEY(graph_version_id) REFERENCES knowledge_graph_version(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS knowledge_relation_source(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,relation_id BIGINT UNSIGNED NOT NULL,source_chunk_id BIGINT UNSIGNED NOT NULL,evidence_type VARCHAR(32) NOT NULL,citation_text VARCHAR(1000) NULL,confidence DECIMAL(6,4) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_relation_source(relation_id,source_chunk_id),CONSTRAINT fk_relation_source_relation FOREIGN KEY(relation_id) REFERENCES knowledge_relation(id) ON DELETE RESTRICT,CONSTRAINT fk_relation_source_chunk FOREIGN KEY(source_chunk_id) REFERENCES source_chunk(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP PROCEDURE IF EXISTS stage08_add_column;
DELIMITER $$
CREATE PROCEDURE stage08_add_column(IN p_table VARCHAR(64),IN p_column VARCHAR(64),IN p_ddl TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=p_table AND column_name=p_column) THEN SET @ddl=p_ddl;PREPARE s FROM @ddl;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL stage08_add_column('knowledge_point','course_id','ALTER TABLE knowledge_point ADD COLUMN course_id BIGINT UNSIGNED NULL');
CALL stage08_add_column('knowledge_point','chapter_id','ALTER TABLE knowledge_point ADD COLUMN chapter_id BIGINT UNSIGNED NULL');
CALL stage08_add_column('knowledge_point','status','ALTER TABLE knowledge_point ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT ''ACTIVE''');
CALL stage08_add_column('knowledge_point','content_version','ALTER TABLE knowledge_point ADD COLUMN content_version VARCHAR(64) NULL');
CALL stage08_add_column('knowledge_point','metadata_json','ALTER TABLE knowledge_point ADD COLUMN metadata_json JSON NULL');
CALL stage08_add_column('knowledge_relation','course_id','ALTER TABLE knowledge_relation ADD COLUMN course_id BIGINT UNSIGNED NULL');
CALL stage08_add_column('knowledge_relation','graph_version_id','ALTER TABLE knowledge_relation ADD COLUMN graph_version_id BIGINT UNSIGNED NULL');
CALL stage08_add_column('knowledge_relation','relation_code','ALTER TABLE knowledge_relation ADD COLUMN relation_code VARCHAR(64) NULL');
CALL stage08_add_column('knowledge_relation','source_knowledge_point_id','ALTER TABLE knowledge_relation ADD COLUMN source_knowledge_point_id BIGINT UNSIGNED NULL');
CALL stage08_add_column('knowledge_relation','target_knowledge_point_id','ALTER TABLE knowledge_relation ADD COLUMN target_knowledge_point_id BIGINT UNSIGNED NULL');
CALL stage08_add_column('knowledge_relation','status','ALTER TABLE knowledge_relation ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT ''DRAFT''');
CALL stage08_add_column('knowledge_relation','published_at','ALTER TABLE knowledge_relation ADD COLUMN published_at DATETIME(3) NULL');
CALL stage08_add_column('knowledge_relation','created_by','ALTER TABLE knowledge_relation ADD COLUMN created_by BIGINT UNSIGNED NULL');
DROP PROCEDURE stage08_add_column;
