package com.xyz.question_bank_management_system.modules.recommendation.service.impl;
import com.xyz.question_bank_management_system.exception.*; import com.xyz.question_bank_management_system.modules.knowledge.entity.QbKnowledgePoint; import com.xyz.question_bank_management_system.modules.knowledge.mapper.QbKnowledgePointMapper; import com.xyz.question_bank_management_system.modules.learning.entity.*; import com.xyz.question_bank_management_system.modules.learning.mapper.*; import com.xyz.question_bank_management_system.modules.profile.entity.StudentProfileSnapshot; import com.xyz.question_bank_management_system.modules.profile.mapper.StudentProfileSnapshotMapper; import com.xyz.question_bank_management_system.modules.recommendation.dto.*; import com.xyz.question_bank_management_system.modules.recommendation.entity.*; import com.xyz.question_bank_management_system.modules.recommendation.mapper.RecommendationMapper; import com.xyz.question_bank_management_system.modules.recommendation.service.ResourceRecommendationService; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.util.StringUtils; import java.math.*; import java.util.*;
@Service @RequiredArgsConstructor public class ResourceRecommendationServiceImpl implements ResourceRecommendationService {
 private final RecommendationMapper mapper; private final QbKnowledgePointMapper pointMapper; private final QbLearningResourceMapper resourceMapper; private final QbLearningResourceTargetMapper targetMapper; private final ResourceKnowledgeMapper resourceKnowledgeMapper; private final StudentProfileSnapshotMapper snapshotMapper;
 @Override @Transactional public List<StudentResourceRecommendation> refresh(Long userId){List<QbKnowledgePoint> weak=pointMapper.selectWeakest(userId,5);Map<Long,Long> targetPoint=new LinkedHashMap<>();for(QbKnowledgePoint p:weak)for(QbLearningResource r:resourceMapper.selectList(null,p.getId(),4))targetPoint.putIfAbsent(r.getId(),p.getId());for(QbLearningResource r:targetMapper.selectResourcesByStudentId(userId,12))targetPoint.putIfAbsent(r.getId(),firstKnowledge(r));List<StudentProfileSnapshot> snapshots=snapshotMapper.selectRecent(userId,1);int rank=1;for(Map.Entry<Long,Long> e:targetPoint.entrySet()){StudentResourceRecommendation rec=new StudentResourceRecommendation();rec.setUserId(userId);rec.setResourceId(e.getKey());rec.setKnowledgePointId(e.getValue());rec.setProfileSnapshotId(snapshots.isEmpty()?null:snapshots.get(0).getId());rec.setRecommendationType(e.getValue()==null?"learn":"remedial");rec.setRankNo(rank);rec.setRecommendScore(BigDecimal.valueOf(Math.max(0.1,1.0-(rank-1)*0.05)).setScale(4,RoundingMode.HALF_UP));rec.setDifficultyMatchScore(BigDecimal.ONE);rec.setReasonText(e.getValue()==null?"教师或系统定向投放的学习资源":"针对当前薄弱知识点的学习资源");rec.setStatus("recommended");mapper.upsert(rec);rank++;}return mapper.listByUser(userId);}
 @Override public List<StudentResourceRecommendation> mine(Long userId){return mapper.listByUser(userId);}
 @Override @Transactional public void updateStatus(Long id,RecommendationStatusRequest req,Long userId){String status=req==null?null:req.getStatus();if(status==null||!Set.of("recommended","viewed","started","completed","skipped","expired").contains(status))throw BizException.of(ErrorCode.PARAM_ERROR,"推荐状态不合法");if(mapper.updateStatus(id,userId,status)==0)throw BizException.of(ErrorCode.NOT_FOUND,"推荐记录不存在");}
 @Override @Transactional public Long feedback(Long resourceId,ResourceFeedbackRequest req,Long userId){if(req==null||!StringUtils.hasText(req.getFeedbackType())||!Set.of("helpful","difficulty","relevance","quality","report").contains(req.getFeedbackType()))throw BizException.of(ErrorCode.PARAM_ERROR,"反馈类型不合法");if(resourceMapper.selectById(resourceId)==null)throw BizException.of(ErrorCode.NOT_FOUND,"学习资源不存在");if(req.getRating()!=null&&(req.getRating().compareTo(BigDecimal.ZERO)<0||req.getRating().compareTo(BigDecimal.valueOf(5))>0))throw BizException.of(ErrorCode.PARAM_ERROR,"评分必须在 0 到 5 之间");if(req.getRecommendationId()!=null){StudentResourceRecommendation rec=mapper.selectOwned(req.getRecommendationId(),userId);if(rec==null||!Objects.equals(rec.getResourceId(),resourceId))throw BizException.of(ErrorCode.FORBIDDEN,"不能反馈其他推荐记录");}ResourceFeedback f=new ResourceFeedback();f.setUserId(userId);f.setResourceId(resourceId);f.setRecommendationId(req.getRecommendationId());f.setFeedbackType(req.getFeedbackType());f.setRating(req.getRating());f.setFeedbackValue(req.getFeedbackValue());f.setFeedbackText(req.getFeedbackText());mapper.insertFeedback(f);return f.getId();}
 private Long firstKnowledge(QbLearningResource resource){List<ResourceKnowledge> r=resourceKnowledgeMapper.selectByResourceId(resource.getId());return r.isEmpty()?null:r.get(0).getKnowledgePointId();}
}
