package com.xyz.question_bank_management_system.modules.recommendation.mapper;
import com.xyz.question_bank_management_system.modules.recommendation.entity.*; import org.apache.ibatis.annotations.*; import java.util.List;
@Mapper public interface RecommendationMapper {
 @Insert("INSERT INTO student_resource_recommendation(user_id,resource_id,goal_id,knowledge_point_id,skill_id,profile_snapshot_id,path_id,recommendation_type,rank_no,recommend_score,difficulty_match_score,reason_text,status,recommended_at,updated_at) VALUES(#{userId},#{resourceId},#{goalId},#{knowledgePointId},#{skillId},#{profileSnapshotId},#{pathId},#{recommendationType},#{rankNo},#{recommendScore},#{difficultyMatchScore},#{reasonText},#{status},NOW(3),NOW(3)) ON DUPLICATE KEY UPDATE knowledge_point_id=VALUES(knowledge_point_id),profile_snapshot_id=VALUES(profile_snapshot_id),recommendation_type=VALUES(recommendation_type),rank_no=VALUES(rank_no),recommend_score=VALUES(recommend_score),difficulty_match_score=VALUES(difficulty_match_score),reason_text=VALUES(reason_text),updated_at=NOW(3)") @Options(useGeneratedKeys=true,keyProperty="id") int upsert(StudentResourceRecommendation e);
 @Select("SELECT * FROM student_resource_recommendation WHERE user_id=#{userId} ORDER BY CASE status WHEN 'recommended' THEN 0 WHEN 'viewed' THEN 1 WHEN 'started' THEN 2 ELSE 3 END,rank_no,id DESC") List<StudentResourceRecommendation> listByUser(@Param("userId") Long userId);
 @Select("SELECT * FROM student_resource_recommendation WHERE id=#{id} AND user_id=#{userId}") StudentResourceRecommendation selectOwned(@Param("id") Long id,@Param("userId") Long userId);
 @Update("UPDATE student_resource_recommendation SET status=#{status},updated_at=NOW(3) WHERE id=#{id} AND user_id=#{userId}") int updateStatus(@Param("id") Long id,@Param("userId") Long userId,@Param("status") String status);
 @Insert("INSERT INTO resource_feedback(user_id,resource_id,recommendation_id,feedback_type,rating,feedback_value,feedback_text,created_at) VALUES(#{userId},#{resourceId},#{recommendationId},#{feedbackType},#{rating},#{feedbackValue},#{feedbackText},NOW(3))") @Options(useGeneratedKeys=true,keyProperty="id") int insertFeedback(ResourceFeedback e);
}
