package com.xyz.question_bank_management_system.modules.source.service.impl;
import com.xyz.question_bank_management_system.exception.*; import com.xyz.question_bank_management_system.modules.knowledge.mapper.KnowledgePointMapper; import com.xyz.question_bank_management_system.modules.learning.mapper.QbLearningResourceMapper; import com.xyz.question_bank_management_system.modules.source.dto.*; import com.xyz.question_bank_management_system.modules.source.entity.*; import com.xyz.question_bank_management_system.modules.source.mapper.*; import com.xyz.question_bank_management_system.modules.source.service.SourceEvidenceService; import com.xyz.question_bank_management_system.util.HashUtil; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.util.StringUtils; import org.springframework.web.multipart.MultipartFile;
import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.math.*; import java.util.*; import java.util.zip.*;

@Service @RequiredArgsConstructor public class SourceEvidenceServiceImpl implements SourceEvidenceService {
    private static final long MAX_FILE_SIZE=5*1024*1024L; private static final int CHUNK_SIZE=1200;
    private final FileAssetMapper fileMapper; private final SourceDocumentMapper documentMapper; private final SourceChunkMapper chunkMapper; private final EvidenceLinkMapper linkMapper; private final KnowledgePointMapper knowledgeMapper; private final QbLearningResourceMapper resourceMapper;
    @Value("${app.file.storage-dir:uploads}") private String storageDir;
    @Override @Transactional public Long uploadDocument(MultipartFile file, SourceDocumentUploadRequest request, Long operatorId) {
        if(file==null||file.isEmpty()) throw BizException.of(ErrorCode.PARAM_ERROR,"请选择来源文件"); if(file.getSize()>MAX_FILE_SIZE) throw BizException.of(ErrorCode.PARAM_ERROR,"来源文件不能超过 5MB");
        String name=Objects.requireNonNullElse(file.getOriginalFilename(),"source.txt"); String ext=extension(name); String content=readText(file,ext); String hash=HashUtil.sha256(content); Path target=store(file,ext,hash);
        FileAsset asset=new FileAsset(); asset.setBizType("source_document"); asset.setFileName(name); asset.setFileExt(ext); asset.setMimeType(file.getContentType()); asset.setStorageType("local"); asset.setStoragePath(target.toString()); asset.setFileSize(file.getSize()); asset.setFileHash(hash); asset.setUploadedBy(operatorId); fileMapper.insert(asset);
        SourceDocument doc=new SourceDocument(); doc.setTitle(text(request==null?null:request.getTitle(),name)); doc.setDocumentType(enumText(request==null?null:request.getDocumentType(),Set.of("textbook","official_doc","paper","standard","course","document"),"document")); doc.setAuthorOrg(trim(request==null?null:request.getAuthorOrg())); doc.setSourceUrl(trim(request==null?null:request.getSourceUrl())); doc.setFileAssetId(asset.getId()); doc.setVersion(trim(request==null?null:request.getVersion())); doc.setAuthorityLevel(authority(request==null?null:request.getAuthorityLevel())); doc.setContentHash(hash); doc.setParseStatus("pending"); documentMapper.insert(doc); asset.setBizId(doc.getId()); fileMapper.updateBizId(asset);
        try { chunkMapper.batchInsert(chunk(doc.getId(),content)); documentMapper.updateParseStatus(doc.getId(),"parsed"); } catch(RuntimeException e){ documentMapper.updateParseStatus(doc.getId(),"failed"); throw e; }
        return doc.getId();
    }
    @Override public List<SourceDocument> documents(){return documentMapper.selectAll();}
    @Override public List<SourceChunk> chunks(Long id){requireDocument(id);return chunkMapper.selectByDocumentId(id);}
    @Override @Transactional public Long linkKnowledge(Long kp, EvidenceLinkRequest req, Long uid){if(knowledgeMapper.selectById(kp)==null)throw BizException.of(ErrorCode.NOT_FOUND,"知识点不存在"); SourceChunk c=requireChunk(req); KnowledgeSource e=new KnowledgeSource();e.setKnowledgePointId(kp);e.setSourceChunkId(c.getId());e.setSupportType(enumText(req.getSupportType(),Set.of("definition","support","example","prerequisite"),"support"));e.setRelevanceScore(score(req.getRelevanceScore(),null));e.setConfidence(score(req.getConfidence(),BigDecimal.ONE));e.setLinkMethod(enumText(req.getLinkMethod(),Set.of("manual","llm","rule","retrieval"),"manual"));e.setReviewStatus(enumText(req.getReviewStatus(),Set.of("pending","pass","reject"),"pending"));e.setReviewedBy(uid);linkMapper.upsertKnowledge(e);return e.getId();}
    @Override @Transactional public Long linkResource(Long resourceId,EvidenceLinkRequest req){if(resourceMapper.selectById(resourceId)==null)throw BizException.of(ErrorCode.NOT_FOUND,"学习资源不存在");SourceChunk c=requireChunk(req);ResourceSource e=new ResourceSource();e.setResourceId(resourceId);e.setSourceChunkId(c.getId());e.setSupportType(enumText(req.getSupportType(),Set.of("grounding","citation","example"),"grounding"));e.setRelevanceScore(score(req.getRelevanceScore(),null));e.setCitationOrder(req.getCitationOrder());linkMapper.upsertResource(e);return e.getId();}
    @Override public List<KnowledgeSource> knowledgeEvidence(Long id){return linkMapper.byKnowledge(id);}
    @Override public List<ResourceSource> resourceEvidence(Long id){return linkMapper.byResource(id);}
    private SourceDocument requireDocument(Long id){SourceDocument d=documentMapper.selectById(id);if(d==null)throw BizException.of(ErrorCode.NOT_FOUND,"来源文档不存在");return d;}
    private SourceChunk requireChunk(EvidenceLinkRequest r){if(r==null||r.getSourceChunkId()==null)throw BizException.of(ErrorCode.PARAM_ERROR,"证据切片不能为空");SourceChunk c=chunkMapper.selectById(r.getSourceChunkId());if(c==null)throw BizException.of(ErrorCode.NOT_FOUND,"证据切片不存在");return c;}
    private List<SourceChunk> chunk(Long doc,String text){List<SourceChunk> out=new ArrayList<>();int start=0,index=0;while(start<text.length()){int end=Math.min(text.length(),start+CHUNK_SIZE);if(end<text.length()){int br=text.lastIndexOf('\n',end);if(br>start+CHUNK_SIZE/2)end=br;}String part=text.substring(start,end).trim();if(!part.isEmpty()){SourceChunk c=new SourceChunk();c.setDocumentId(doc);c.setChunkIndex(index++);c.setContent(part);c.setContentHash(HashUtil.sha256(part));c.setTokenCount(part.length());out.add(c);}start=end;}return out;}
    private Path store(MultipartFile file,String ext,String hash){try{Path root=Paths.get(storageDir).toAbsolutePath().normalize();Path dir=root.resolve("source-documents");Files.createDirectories(dir);Path target=dir.resolve(hash+(ext.isBlank()?"":"."+ext));file.transferTo(target);return target;}catch(IOException e){throw BizException.of(ErrorCode.BIZ_ERROR,"保存来源文件失败");}}
    private String readText(MultipartFile file,String ext){try{String s;if("docx".equals(ext)){s=docx(file.getBytes());}else if(Set.of("txt","md","csv","json","sql","html","htm").contains(ext)){s=new String(file.getBytes(),StandardCharsets.UTF_8);if("html".equals(ext)||"htm".equals(ext))s=s.replaceAll("(?is)<script.*?</script>|<style.*?</style>|<[^>]+>"," ");}else throw BizException.of(ErrorCode.PARAM_ERROR,"仅支持 txt、md、csv、json、sql、html、docx 来源文件");s=s.replaceAll("[ \\t\\r]+"," ").replaceAll("\\n{3,}","\\n\\n").trim();if(!StringUtils.hasText(s))throw BizException.of(ErrorCode.PARAM_ERROR,"来源文件没有可用文本");return s;}catch(IOException e){throw BizException.of(ErrorCode.BIZ_ERROR,"读取来源文件失败");}}
    private String docx(byte[] b)throws IOException{try(ZipInputStream z=new ZipInputStream(new ByteArrayInputStream(b),StandardCharsets.UTF_8)){ZipEntry e;while((e=z.getNextEntry())!=null)if("word/document.xml".equals(e.getName()))return new String(z.readAllBytes(),StandardCharsets.UTF_8).replaceAll("(?s)</w:p>","\\n").replaceAll("(?s)<[^>]+>"," ");}return "";}
    private String extension(String name){int p=name.lastIndexOf('.');return p<0?"":name.substring(p+1).toLowerCase(Locale.ROOT);} private String trim(String x){return StringUtils.hasText(x)?x.trim():null;} private String text(String x,String f){String t=trim(x);return t==null?f:t;} private String enumText(String x,Set<String>s,String f){String t=text(x,f).toLowerCase(Locale.ROOT);if(!s.contains(t))throw BizException.of(ErrorCode.PARAM_ERROR,"参数值不受支持");return t;} private Integer authority(Integer n){if(n==null)return 3;if(n<1||n>5)throw BizException.of(ErrorCode.PARAM_ERROR,"可信等级必须为 1 到 5");return n;} private BigDecimal score(BigDecimal v,BigDecimal f){if(v==null)return f;if(v.compareTo(BigDecimal.ZERO)<0||v.compareTo(BigDecimal.ONE)>0)throw BizException.of(ErrorCode.PARAM_ERROR,"相关度或置信度必须在 0 到 1 之间");return v;}
}
