package com.xyz.question_bank_management_system.modules.course.service.impl;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.xyz.question_bank_management_system.config.CorrelationContext;
import com.xyz.question_bank_management_system.exception.*;
import com.xyz.question_bank_management_system.modules.course.service.*;
import com.xyz.question_bank_management_system.modules.knowledge.entity.KnowledgePoint;
import com.xyz.question_bank_management_system.modules.knowledge.mapper.KnowledgePointMapper;
import com.xyz.question_bank_management_system.modules.learning.entity.*;
import com.xyz.question_bank_management_system.modules.learning.mapper.LearningPathV1Mapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import java.util.*;
@Service @RequiredArgsConstructor public class PathRefreshApplicationServiceImpl implements PathRefreshApplicationService {
 private final LearningPathV1Mapper mapper;private final PathPlanningService planner;private final PathEventDetector detector;private final KnowledgePointMapper pointMapper;private final ObjectMapper objectMapper;
 @Override @Transactional public Map<String,Object> create(Long userId,Long courseId,Long target,String key){if(!StringUtils.hasText(key))throw BizException.of(ErrorCode.PARAM_ERROR,"Idempotency-Key 不能为空");LearningPath existing=mapper.selectByIdempotency(userId,key);if(existing!=null)return view(existing);PathPlanningService.PlanResult plan=planner.plan(userId,courseId,target);LearningPath p=new LearningPath();p.setPathCode("path_"+UUID.randomUUID().toString().replace("-",""));p.setUserId(userId);p.setCourseId(courseId);p.setTargetKnowledgePointId(target);p.setStatus("ACTIVE");p.setCurrentVersion(1L);p.setIdempotencyKey(key);p.setTitle("个性化学习路径");mapper.insertPath(p);LearningPathVersion v=version(p,1L,"BASELINE",plan,"INITIAL_CREATE");mapper.insertVersion(v);mapper.batchInsertSteps(steps(p.getId(),v.getId(),plan.knowledgePointIds()));mapper.insertProgress(p.getId());return view(p);}
 @Override public Map<String,Object> get(Long userId,String code,boolean admin){LearningPath p=require(code);if(!admin&&!Objects.equals(p.getUserId(),userId))throw BizException.of(ErrorCode.FORBIDDEN,"无权查看该路径");return view(p);}
 @Override @Transactional public Map<String,Object> completeStep(Long userId,String code,String stepCode){LearningPath p=mapper.selectByCodeForUpdate(code);if(p==null)throw BizException.of(ErrorCode.NOT_FOUND,"路径不存在");if(!Objects.equals(p.getUserId(),userId))throw BizException.of(ErrorCode.FORBIDDEN,"无权完成该路径步骤");LearningPathItem step=mapper.selectActiveStepForUpdate(code,stepCode);if(step==null)throw BizException.of(ErrorCode.NOT_FOUND,"当前路径版本不存在该步骤");if("PENDING".equals(step.getStatus())&&mapper.completeActiveStep(step.getId())!=1)throw BizException.of(ErrorCode.CONFLICT,"路径步骤状态已变化");return view(p);}
 @Override @Transactional public Map<String,Object> refresh(Long userId,String code,String reason,boolean admin){LearningPath p=mapper.selectByCodeForUpdate(code);if(p==null)throw BizException.of(ErrorCode.NOT_FOUND,"路径不存在");if(!admin&&!Objects.equals(p.getUserId(),userId))throw BizException.of(ErrorCode.FORBIDDEN,"无权刷新该路径");LearningPathVersion old=mapper.selectActiveVersionForUpdate(p.getId());List<LearningPathItem> oldSteps=mapper.selectSteps(old.getId());List<Long> previous=oldSteps.stream().map(LearningPathItem::getKnowledgePointId).toList();List<LearningPathItem> completedPrefix=new ArrayList<>();for(LearningPathItem step:oldSteps){if(!"COMPLETED".equals(step.getStatus()))break;completedPrefix.add(step);}PathPlanningService.PlanResult plan=planner.plan(p.getUserId(),p.getCourseId(),p.getTargetKnowledgePointId());List<Long> candidate=new ArrayList<>(completedPrefix.stream().map(LearningPathItem::getKnowledgePointId).toList());for(Long id:plan.knowledgePointIds())if(!candidate.contains(id))candidate.add(id);if(previous.equals(candidate)){Map<String,Object> m=new LinkedHashMap<>(view(p));m.put("result","ACTIVE_UNCHANGED");m.put("reason","EVENT_NO_CHANGE");return m;}long next=old.getVersion()+1;LearningPathVersion v=version(p,next,"ADAPTIVE_UPDATED",plan,reason);mapper.supersede(old.getId());mapper.insertVersion(v);mapper.batchInsertSteps(steps(p.getId(),v.getId(),candidate,completedPrefix));mapper.updateCurrentVersion(p.getId(),next);p.setCurrentVersion(next);writeLog(p,old,next,reason,previous,candidate);return view(p);}
 @Override @Transactional public Map<String,Object> evaluateEvent(String code,Map<String,Object> event){LearningPath p=require(code);LearningPathProgress progress=mapper.selectProgressForUpdate(p.getId());Set<String> events=detector.detect(progress,event);if(events.isEmpty()){Map<String,Object> m=new LinkedHashMap<>(view(p));m.put("result","NO_PATH_EVENT");return m;}return refresh(p.getUserId(),code,String.join(",",events),true);}
 private LearningPath require(String c){LearningPath p=mapper.selectByCode(c);if(p==null)throw BizException.of(ErrorCode.NOT_FOUND,"路径不存在");return p;}
 private LearningPathVersion version(LearningPath p,long n,String mode,PathPlanningService.PlanResult plan,String reason){LearningPathVersion v=new LearningPathVersion();v.setPathId(p.getId());v.setVersion(n);v.setPathMode(mode);v.setBasedOnProfileVersion(plan.profileVersion());v.setGraphVersion(plan.graphVersion());v.setPolicyVersion(plan.policyVersion());v.setModelVersion("deterministic_path_v1");v.setStatus("ACTIVE");v.setChangeReason(reason);v.setCorrelationId(CorrelationContext.get());return v;}
 private List<LearningPathItem> steps(Long pathId,Long versionId,List<Long> ids){return steps(pathId,versionId,ids,List.of());}
 private List<LearningPathItem> steps(Long pathId,Long versionId,List<Long> ids,List<LearningPathItem> completedPrefix){List<LearningPathItem> out=new ArrayList<>();int i=0;for(Long id:ids){LearningPathItem x=new LearningPathItem();x.setPathId(pathId);x.setPathVersionId(versionId);x.setPathStepCode(String.format("ps_%05d",++i));x.setOrderNo(i);x.setKnowledgePointId(id);x.setStage("LEARNING");LearningPathItem completed=i<=completedPrefix.size()?completedPrefix.get(i-1):null;x.setStatus(completed==null?"PENDING":"COMPLETED");x.setCompletedAt(completed==null?null:completed.getCompletedAt());x.setReasonCode("PREREQUISITE_ORDER");x.setDecisionReason("课程图先修闭包与稳定拓扑排序");out.add(x);}return out;}
 private Map<String,Object> view(LearningPath p){LearningPathVersion v=mapper.selectActiveVersion(p.getId());List<Map<String,Object>> steps=mapper.selectSteps(v.getId()).stream().map(x->{KnowledgePoint kp=pointMapper.selectById(x.getKnowledgePointId());Map<String,Object> m=new LinkedHashMap<>();m.put("pathStepId",x.getPathStepCode());m.put("orderNo",x.getOrderNo());m.put("knowledgePointId",x.getKnowledgePointId());m.put("knowledgePointName",kp==null?"":kp.getName());m.put("stage",x.getStage());m.put("status",x.getStatus());m.put("reasonCode",x.getReasonCode());m.put("decisionReason",x.getDecisionReason());return m;}).toList();Map<String,Object> m=new LinkedHashMap<>();m.put("pathCode",p.getPathCode());m.put("courseId",p.getCourseId());m.put("targetKnowledgePointId",p.getTargetKnowledgePointId());m.put("currentVersion",p.getCurrentVersion());m.put("status",p.getStatus());m.put("graphVersion",v.getGraphVersion());m.put("profileVersion",v.getBasedOnProfileVersion());m.put("steps",steps);return m;}
 private void writeLog(LearningPath p,LearningPathVersion old,long next,String reason,List<Long>a,List<Long>b){try{PathUpdateLog l=new PathUpdateLog();l.setPathId(p.getId());l.setOldVersion(old.getVersion());l.setNewVersion(next);l.setTriggerEventTypesJson(objectMapper.writeValueAsString(List.of(reason)));Set<Long> added=new LinkedHashSet<>(b);added.removeAll(a);Set<Long> removed=new LinkedHashSet<>(a);removed.removeAll(b);Set<Long> retained=new LinkedHashSet<>(a);retained.retainAll(b);l.setAddedStepIdsJson(objectMapper.writeValueAsString(added));l.setRemovedStepIdsJson(objectMapper.writeValueAsString(removed));l.setRetainedStepIdsJson(objectMapper.writeValueAsString(retained));l.setTriggerInteractionIdsJson("[]");l.setAffectedKnowledgePointIdsJson(objectMapper.writeValueAsString(added));l.setCorrelationId(CorrelationContext.get());mapper.insertUpdateLog(l);}catch(Exception ex){throw new IllegalStateException(ex);}}
}
