package com.xyz.question_bank_management_system.modules.course.service.impl;
import com.xyz.question_bank_management_system.exception.*;
import com.xyz.question_bank_management_system.modules.course.service.PathPlanningService;
import com.xyz.question_bank_management_system.modules.knowledge.entity.*;
import com.xyz.question_bank_management_system.modules.knowledge.mapper.*;
import com.xyz.question_bank_management_system.modules.knowledge.repository.Neo4jKnowledgeGraphRepository;
import com.xyz.question_bank_management_system.modules.profile.entity.*;
import com.xyz.question_bank_management_system.modules.profile.mapper.*;
import com.xyz.question_bank_management_system.modules.profile.mapper.StudentProfileSnapshotMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.math.BigDecimal;
import java.util.*;
@Service @RequiredArgsConstructor public class PathPlanningServiceImpl implements PathPlanningService {
 private final KnowledgeGraphVersionMapper versionMapper;private final KnowledgeGraphVersionRelationMapper relationMapper;private final KnowledgePointMapper pointMapper;private final Neo4jKnowledgeGraphRepository graph;private final StudentKnowledgeStateMapper stateMapper;private final StudentProfileSnapshotMapper snapshotMapper;
 @Override public PlanResult plan(Long userId,Long courseId,Long target){KnowledgeGraphVersion version=versionMapper.selectActive(courseId);if(version==null||!graph.available())throw BizException.of(ErrorCode.KNOWLEDGE_GRAPH_UNAVAILABLE,"当前课程没有可用的 ACTIVE 知识图谱");if(pointMapper.selectActiveByIdAndCourse(target,courseId)==null)throw BizException.of(ErrorCode.PARAM_ERROR,"目标知识点不是当前课程可用于路径的 ACTIVE 知识点");Set<Long> allowed=pointMapper.selectActivePathEligibleByCourse(courseId).stream().map(KnowledgePoint::getId).collect(java.util.stream.Collectors.toSet());Set<Long> closure=new LinkedHashSet<>(graph.prerequisiteClosure(courseId,version.getVersionCode(),target));closure.retainAll(allowed);closure.add(target);Map<Long,StudentKnowledgeState> states=new HashMap<>();for(StudentKnowledgeState s:stateMapper.selectByUserAndCourse(userId,courseId))states.put(s.getKnowledgePointId(),s);closure.removeIf(id->{if(Objects.equals(id,target))return false;StudentKnowledgeState s=states.get(id);return s!=null&&ge(s.getMasteryValue(),"0.80")&&ge(s.getConfidence(),"0.60");});List<KnowledgeGraphVersionRelation> rels=relationMapper.selectByVersion(version.getId()).stream().filter(r->"PREREQUISITE".equals(r.getRelationType())&&closure.contains(r.getSourceKnowledgePointId())&&closure.contains(r.getTargetKnowledgePointId())).toList();Map<Long,Integer> indegree=new HashMap<>();Map<Long,List<Long>> next=new HashMap<>();for(Long id:closure)indegree.put(id,0);for(KnowledgeGraphVersionRelation r:rels){next.computeIfAbsent(r.getSourceKnowledgePointId(),x->new ArrayList<>()).add(r.getTargetKnowledgePointId());indegree.compute(r.getTargetKnowledgePointId(),(k,v)->v+1);}PriorityQueue<Long> ready=new PriorityQueue<>((a,b)->{StudentKnowledgeState sa=states.get(a),sb=states.get(b);BigDecimal ma=sa==null?BigDecimal.ZERO:sa.getMasteryValue(),mb=sb==null?BigDecimal.ZERO:sb.getMasteryValue();int c=ma.compareTo(mb);return c!=0?c:Long.compare(a,b);});indegree.forEach((k,v)->{if(v==0)ready.add(k);});List<Long> ordered=new ArrayList<>();while(!ready.isEmpty()){Long n=ready.poll();ordered.add(n);for(Long x:next.getOrDefault(n,List.of()))if(indegree.compute(x,(k,v)->v-1)==0)ready.add(x);}if(ordered.size()!=closure.size())throw BizException.of(ErrorCode.CONFLICT,"知识图谱先修关系包含环");StudentProfileSnapshot snapshot=snapshotMapper.selectLatest(userId,courseId);return new PlanResult(ordered,version.getVersionCode(),snapshot==null?0:Objects.requireNonNullElse(snapshot.getProfileVersion(),0L),"path_policy_v1");}
 private boolean ge(BigDecimal value,String threshold){return value!=null&&value.compareTo(new BigDecimal(threshold))>=0;}
}
