USE question_bank;
CREATE TABLE IF NOT EXISTS student_resource_recommendation (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,resource_id BIGINT UNSIGNED NOT NULL,goal_id BIGINT UNSIGNED NULL,knowledge_point_id BIGINT UNSIGNED NULL,skill_id BIGINT UNSIGNED NULL,profile_snapshot_id BIGINT UNSIGNED NULL,path_id BIGINT UNSIGNED NULL,recommendation_type VARCHAR(32) NOT NULL DEFAULT 'remedial',rank_no INT NULL,recommend_score DECIMAL(6,4) NULL,difficulty_match_score DECIMAL(6,4) NULL,reason_text VARCHAR(2000) NULL,status VARCHAR(24) NOT NULL DEFAULT 'recommended',recommended_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY(id),UNIQUE KEY uk_student_resource_recommendation(user_id,resource_id),KEY idx_recommendation_user_status(user_id,status,rank_no),CONSTRAINT fk_recommendation_user FOREIGN KEY(user_id) REFERENCES sys_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_recommendation_resource FOREIGN KEY(resource_id) REFERENCES qb_learning_resource(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_recommendation_point FOREIGN KEY(knowledge_point_id) REFERENCES knowledge_point(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_recommendation_snapshot FOREIGN KEY(profile_snapshot_id) REFERENCES student_profile_snapshot(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_recommendation_path FOREIGN KEY(path_id) REFERENCES learning_path(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT ck_recommendation_scores CHECK((recommend_score IS NULL OR recommend_score BETWEEN 0 AND 1) AND (difficulty_match_score IS NULL OR difficulty_match_score BETWEEN 0 AND 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS resource_feedback (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,resource_id BIGINT UNSIGNED NOT NULL,recommendation_id BIGINT UNSIGNED NULL,feedback_type VARCHAR(32) NOT NULL,rating DECIMAL(4,2) NULL,feedback_value VARCHAR(255) NULL,feedback_text VARCHAR(2000) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(id),KEY idx_resource_feedback_user(user_id,created_at),KEY idx_resource_feedback_resource(resource_id,created_at),CONSTRAINT fk_resource_feedback_user FOREIGN KEY(user_id) REFERENCES sys_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_resource_feedback_resource FOREIGN KEY(resource_id) REFERENCES qb_learning_resource(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_resource_feedback_recommendation FOREIGN KEY(recommendation_id) REFERENCES student_resource_recommendation(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT ck_resource_feedback_rating CHECK(rating IS NULL OR rating BETWEEN 0 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
