package com.xyz.question_bank_management_system.modules.agent.controller;
import com.xyz.question_bank_management_system.common.ApiResponse;import com.xyz.question_bank_management_system.modules.agent.service.ResourceGenerationWorkflow;import com.xyz.question_bank_management_system.util.SecurityContextUtil;import lombok.Data;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController @RequiredArgsConstructor public class PersonalizedResourceController {private final ResourceGenerationWorkflow workflow;
 @PostMapping("/api/v1/personalized-resources/jobs") @PreAuthorize("hasRole('STUDENT')") public ApiResponse<Map<String,Object>> start(@RequestHeader("Idempotency-Key")String key,@RequestBody StartRequest r){return ApiResponse.ok(workflow.start(SecurityContextUtil.getUserId(),r.pathCode,r.pathStepId,r.providerKey,key));}
 @GetMapping("/api/v1/personalized-resources/jobs/{jobCode}") @PreAuthorize("isAuthenticated()") public ApiResponse<Map<String,Object>> status(@PathVariable String jobCode){return ApiResponse.ok(workflow.status(SecurityContextUtil.getUserId(),jobCode,SecurityContextUtil.currentRoles().contains("ADMIN")));}
 @GetMapping("/api/v1/personalized-resources/{bundleCode}") @PreAuthorize("isAuthenticated()") public ApiResponse<Map<String,Object>> bundle(@PathVariable String bundleCode){return ApiResponse.ok(workflow.bundle(SecurityContextUtil.getUserId(),bundleCode,SecurityContextUtil.currentRoles().contains("ADMIN")));}
 @PostMapping("/api/v1/personalized-resources/{bundleCode}/regenerate") @PreAuthorize("hasRole('STUDENT')") public ApiResponse<Map<String,Object>> regenerate(@PathVariable String bundleCode,@RequestHeader("Idempotency-Key")String key,@RequestBody(required=false)Map<String,Object> body){return ApiResponse.ok(workflow.regenerate(SecurityContextUtil.getUserId(),bundleCode,body==null?null:String.valueOf(body.get("providerKey")),key));}
 @PostMapping("/internal/v1/personalized-resources/decide") @PreAuthorize("hasAuthority('INTERNAL_SERVICE') or hasRole('ADMIN')") public ApiResponse<Map<String,Object>> decide(@RequestBody Map<String,Object> body){return ApiResponse.ok(workflow.decide(String.valueOf(body.getOrDefault("eventType","PROFILE_VALUE_ONLY")),Boolean.TRUE.equals(body.get("hasPublishedBundle"))));}
 @Data public static class StartRequest {private String pathCode;private String pathStepId;private String providerKey;}
}
