CREATE TABLE IF NOT EXISTS resource_bundle(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,bundle_code VARCHAR(64) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,course_id BIGINT UNSIGNED NOT NULL,resource_unit_id BIGINT UNSIGNED NOT NULL,blueprint_id BIGINT UNSIGNED NOT NULL,version BIGINT UNSIGNED NOT NULL,status VARCHAR(24) NOT NULL,profile_version_used BIGINT UNSIGNED NOT NULL,graph_version VARCHAR(64) NOT NULL,policy_version VARCHAR(64) NOT NULL,content_hash CHAR(64) NULL,published_at DATETIME(3) NULL,stale_reason VARCHAR(255) NULL,correlation_id VARCHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_bundle_code(bundle_code),UNIQUE KEY uk_bundle_version(resource_unit_id,version),KEY idx_bundle_user_status(user_id,status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS resource_item(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,bundle_id BIGINT UNSIGNED NOT NULL,item_code VARCHAR(64) NOT NULL,generated_question_code VARCHAR(64) NULL,item_type VARCHAR(32) NOT NULL,purpose VARCHAR(32) NOT NULL,visibility VARCHAR(32) NOT NULL,title VARCHAR(500) NOT NULL,content_json JSON NOT NULL,question_difficulty DECIMAL(6,4) NULL,cognitive_level VARCHAR(24) NULL,grading_key_json JSON NULL,order_no INT NOT NULL,status VARCHAR(24) NOT NULL,normalized_text_hash CHAR(64) NULL,simhash64 BIGINT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_resource_item_code(bundle_id,item_code),UNIQUE KEY uk_generated_question_code(generated_question_code),KEY idx_item_visibility(bundle_id,visibility,status),CONSTRAINT ck_item_visibility CHECK(visibility IN('VISIBLE','HIDDEN_UNTIL_ASSESSMENT','INTERNAL'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS resource_review(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,job_id BIGINT UNSIGNED NOT NULL,bundle_id BIGINT UNSIGNED NULL,blueprint_id BIGINT UNSIGNED NOT NULL,expert_role VARCHAR(64) NOT NULL,result VARCHAR(16) NOT NULL,issue_type VARCHAR(64) NULL,location VARCHAR(255) NULL,description VARCHAR(1000) NULL,repair_target VARCHAR(64) NULL,repair_scope VARCHAR(255) NULL,repair_action VARCHAR(255) NULL,repair_instruction VARCHAR(2000) NULL,critical TINYINT NOT NULL DEFAULT 0,round_no INT NOT NULL,report_json JSON NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),KEY idx_resource_review_job(job_id,round_no,expert_role)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS resource_assessment_release(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,release_code VARCHAR(64) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,bundle_id BIGINT UNSIGNED NOT NULL,resource_item_id BIGINT UNSIGNED NOT NULL,status VARCHAR(24) NOT NULL,released_at DATETIME(3) NOT NULL,expires_at DATETIME(3) NULL,consumed_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_assessment_release_code(release_code),KEY idx_assessment_active(user_id,bundle_id,status,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE resource_knowledge MODIFY COLUMN resource_id BIGINT UNSIGNED NULL;
ALTER TABLE resource_source MODIFY COLUMN resource_id BIGINT UNSIGNED NULL;
DROP PROCEDURE IF EXISTS stage12_add_column;
DELIMITER $$
CREATE PROCEDURE stage12_add_column(IN t VARCHAR(64),IN c VARCHAR(64),IN d TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=t AND column_name=c)THEN SET @x=d;PREPARE s FROM @x;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL stage12_add_column('resource_knowledge','resource_item_id','ALTER TABLE resource_knowledge ADD COLUMN resource_item_id BIGINT UNSIGNED NULL');
CALL stage12_add_column('resource_source','resource_item_id','ALTER TABLE resource_source ADD COLUMN resource_item_id BIGINT UNSIGNED NULL');
CALL stage12_add_column('resource_source','evidence_type','ALTER TABLE resource_source ADD COLUMN evidence_type VARCHAR(32) NULL');
CALL stage12_add_column('resource_source','citation_text','ALTER TABLE resource_source ADD COLUMN citation_text VARCHAR(1000) NULL');
CALL stage12_add_column('resource_source','support_score','ALTER TABLE resource_source ADD COLUMN support_score DECIMAL(6,4) NULL');
DROP PROCEDURE stage12_add_column;
DROP PROCEDURE IF EXISTS stage12_add_index;
DELIMITER $$
CREATE PROCEDURE stage12_add_index(IN t VARCHAR(64),IN i VARCHAR(64),IN d TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name=t AND index_name=i)THEN SET @x=d;PREPARE s FROM @x;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL stage12_add_index('resource_knowledge','uk_resource_item_knowledge','CREATE UNIQUE INDEX uk_resource_item_knowledge ON resource_knowledge(resource_item_id,knowledge_point_id,relation_type)');
DROP PROCEDURE stage12_add_index;
