-- Stage 07B schema. Execute manually after precheck.
USE question_bank;
CREATE TABLE IF NOT EXISTS file_asset (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,biz_type VARCHAR(40) NULL,biz_id BIGINT UNSIGNED NULL,file_name VARCHAR(255) NOT NULL,file_ext VARCHAR(32) NULL,mime_type VARCHAR(128) NULL,storage_type VARCHAR(24) NOT NULL DEFAULT 'local',storage_path VARCHAR(1000) NOT NULL,file_size BIGINT UNSIGNED NULL,file_hash VARCHAR(128) NULL,uploaded_by BIGINT UNSIGNED NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),is_deleted TINYINT NOT NULL DEFAULT 0,
 PRIMARY KEY(id),KEY idx_file_asset_biz(biz_type,biz_id,is_deleted),KEY idx_file_asset_hash(file_hash),CONSTRAINT fk_file_asset_uploader FOREIGN KEY(uploaded_by) REFERENCES sys_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS source_document (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,title VARCHAR(500) NOT NULL,document_type VARCHAR(40) NOT NULL DEFAULT 'document',author_org VARCHAR(255) NULL,source_url VARCHAR(1000) NULL,file_asset_id BIGINT UNSIGNED NULL,version VARCHAR(64) NULL,published_at DATETIME(3) NULL,authority_level TINYINT NOT NULL DEFAULT 3,content_hash VARCHAR(128) NULL,parse_status VARCHAR(24) NOT NULL DEFAULT 'pending',created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),is_deleted TINYINT NOT NULL DEFAULT 0,
 PRIMARY KEY(id),KEY idx_source_document_status(parse_status,authority_level,created_at),KEY idx_source_document_hash(content_hash),CONSTRAINT fk_source_document_asset FOREIGN KEY(file_asset_id) REFERENCES file_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT ck_source_document_authority CHECK(authority_level BETWEEN 1 AND 5),CONSTRAINT ck_source_document_parse CHECK(parse_status IN ('pending','parsed','failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS source_chunk (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,document_id BIGINT UNSIGNED NOT NULL,chunk_index INT NOT NULL DEFAULT 0,section_title VARCHAR(500) NULL,page_start INT NULL,page_end INT NULL,content LONGTEXT NOT NULL,content_hash VARCHAR(128) NULL,token_count INT NULL,vector_ref VARCHAR(255) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(id),UNIQUE KEY uk_source_chunk_document_index(document_id,chunk_index),KEY idx_source_chunk_hash(content_hash),CONSTRAINT fk_source_chunk_document FOREIGN KEY(document_id) REFERENCES source_document(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT ck_source_chunk_index CHECK(chunk_index>=0),CONSTRAINT ck_source_chunk_pages CHECK(page_start IS NULL OR page_end IS NULL OR page_start<=page_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS knowledge_source (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,knowledge_point_id BIGINT UNSIGNED NOT NULL,source_chunk_id BIGINT UNSIGNED NOT NULL,support_type VARCHAR(24) NOT NULL DEFAULT 'support',relevance_score DECIMAL(6,4) NULL,confidence DECIMAL(6,4) NOT NULL DEFAULT 1.0000,link_method VARCHAR(32) NOT NULL DEFAULT 'manual',review_status VARCHAR(24) NOT NULL DEFAULT 'pending',reviewed_by BIGINT UNSIGNED NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(id),UNIQUE KEY uk_knowledge_source(knowledge_point_id,source_chunk_id),KEY idx_knowledge_source_chunk(source_chunk_id),CONSTRAINT fk_knowledge_source_point FOREIGN KEY(knowledge_point_id) REFERENCES knowledge_point(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_knowledge_source_chunk FOREIGN KEY(source_chunk_id) REFERENCES source_chunk(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_knowledge_source_reviewer FOREIGN KEY(reviewed_by) REFERENCES sys_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT ck_knowledge_source_scores CHECK((relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1) AND confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS resource_source (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,resource_id BIGINT UNSIGNED NOT NULL,source_chunk_id BIGINT UNSIGNED NOT NULL,support_type VARCHAR(24) NOT NULL DEFAULT 'grounding',relevance_score DECIMAL(6,4) NULL,citation_order INT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(id),UNIQUE KEY uk_resource_source(resource_id,source_chunk_id),KEY idx_resource_source_chunk(source_chunk_id),CONSTRAINT fk_resource_source_resource FOREIGN KEY(resource_id) REFERENCES qb_learning_resource(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_resource_source_chunk FOREIGN KEY(source_chunk_id) REFERENCES source_chunk(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT ck_resource_source_score CHECK(relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
