CREATE TABLE IF NOT EXISTS resource_interaction(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,interaction_code VARCHAR(64) NOT NULL,interaction_seq BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,course_id BIGINT UNSIGNED NOT NULL,resource_bundle_id BIGINT UNSIGNED NOT NULL,resource_version BIGINT UNSIGNED NOT NULL,resource_unit_id BIGINT UNSIGNED NOT NULL,resource_item_id BIGINT UNSIGNED NOT NULL,generated_question_code VARCHAR(64) NOT NULL,question_purpose VARCHAR(32) NOT NULL,visibility VARCHAR(32) NOT NULL,question_difficulty DECIMAL(6,4) NOT NULL,primary_knowledge_point_id BIGINT UNSIGNED NOT NULL,knowledge_point_weights_json JSON NOT NULL,score_normalized DECIMAL(6,4) NOT NULL,correct TINYINT NOT NULL,status VARCHAR(24) NOT NULL,action_origin VARCHAR(32) NOT NULL,grading_version VARCHAR(64) NOT NULL,answer_json JSON NOT NULL,request_id VARCHAR(128) NOT NULL,correlation_id VARCHAR(64) NOT NULL,client_occurred_at DATETIME(3) NULL,submitted_at DATETIME(3) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_interaction_code(interaction_code),UNIQUE KEY uk_interaction_request(request_id),UNIQUE KEY uk_interaction_seq(user_id,course_id,interaction_seq),KEY idx_interaction_item(resource_item_id,submitted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS profile_evidence_event(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,event_id VARCHAR(64) NOT NULL,interaction_id BIGINT UNSIGNED NOT NULL,consumer_name VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL,retry_count INT NOT NULL DEFAULT 0,processed_at DATETIME(3) NULL,error_message VARCHAR(1000) NULL,PRIMARY KEY(id),UNIQUE KEY uk_profile_evidence_consumer(event_id,consumer_name),KEY idx_profile_evidence_status(status,retry_count)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS outbox_event(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,event_id VARCHAR(64) NOT NULL,aggregate_type VARCHAR(64) NOT NULL,aggregate_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(128) NOT NULL,payload_json JSON NOT NULL,status VARCHAR(24) NOT NULL,retry_count INT NOT NULL DEFAULT 0,next_retry_at DATETIME(3) NULL,correlation_id VARCHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),published_at DATETIME(3) NULL,PRIMARY KEY(id),UNIQUE KEY uk_outbox_event(event_id),KEY idx_outbox_pending(status,next_retry_at,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS resource_action_decision(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,course_id BIGINT UNSIGNED NOT NULL,path_id BIGINT UNSIGNED NOT NULL,path_version BIGINT UNSIGNED NOT NULL,interaction_id BIGINT UNSIGNED NOT NULL,action VARCHAR(24) NOT NULL,reason VARCHAR(64) NOT NULL,correlation_id VARCHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_resource_decision_interaction(interaction_id),KEY idx_resource_decision_path(path_id,path_version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP PROCEDURE IF EXISTS stage13_add_column;
DELIMITER $$
CREATE PROCEDURE stage13_add_column(IN t VARCHAR(64),IN c VARCHAR(64),IN d TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=t AND column_name=c)THEN SET @x=d;PREPARE s FROM @x;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL stage13_add_column('qb_attempt_question','generated_question_code','ALTER TABLE qb_attempt_question ADD COLUMN generated_question_code VARCHAR(64) NULL');
DROP PROCEDURE stage13_add_column;
