package com.xyz.question_bank_management_system.modules.profile.service.impl;
import com.xyz.question_bank_management_system.modules.profile.entity.StudentKnowledgeState;
import com.xyz.question_bank_management_system.modules.profile.model.*;
import com.xyz.question_bank_management_system.modules.profile.service.KnowledgeStateService;
import org.springframework.stereotype.Service;
import java.math.*;
import java.util.*;
@Service public class KnowledgeStateServiceImpl implements KnowledgeStateService {
 private static final BigDecimal LEARNING_RATE=new BigDecimal("0.20");
 @Override public KnowledgeUpdateResult update(StudentKnowledgeState previous,List<ValidatedInteraction> interactions){StudentKnowledgeState state=copy(previous);boolean changed=false;for(ValidatedInteraction i:interactions){if(i.getInteractionSeq()!=null&&state.getLastInteractionSeq()!=null&&i.getInteractionSeq()<=state.getLastInteractionSeq())continue;BigDecimal questionWeight=i.getKnowledgeWeights().getOrDefault(state.getKnowledgePointId(),BigDecimal.ZERO);if(questionWeight.signum()==0)continue;BigDecimal purpose="KNOWLEDGE_ASSESSMENT".equals(i.getQuestionPurpose())?BigDecimal.ONE:new BigDecimal("0.70");BigDecimal evidence=questionWeight.multiply(purpose).multiply(or(i.getGradingConfidence(),BigDecimal.ONE));BigDecimal difficulty=or(i.getQuestionDifficulty(),new BigDecimal("0.50"));BigDecimal factor=BigDecimal.ONE.add(new BigDecimal("0.50").multiply(difficulty.subtract(new BigDecimal("0.50"))));BigDecimal before=or(state.getMasteryValue(),new BigDecimal("0.30"));BigDecimal delta=LEARNING_RATE.multiply(evidence).multiply(or(i.getScoreNormalized(),BigDecimal.ZERO).subtract(before)).multiply(factor);BigDecimal after=clamp(before.add(delta));state.setMasteryValue(after.setScale(4,RoundingMode.HALF_UP));int count=Objects.requireNonNullElse(state.getEvidenceCount(),0)+1;state.setEvidenceCount(count);state.setAttemptCount(Objects.requireNonNullElse(state.getAttemptCount(),0)+1);if(or(i.getScoreNormalized(),BigDecimal.ZERO).compareTo(new BigDecimal("0.9999"))>=0)state.setCorrectCount(Objects.requireNonNullElse(state.getCorrectCount(),0)+1);state.setConfidence(BigDecimal.valueOf(1-Math.exp(-count/5.0)).setScale(4,RoundingMode.HALF_UP));state.setMasteryLevel(level(state.getMasteryValue()));state.setStateVersion(Objects.requireNonNullElse(state.getStateVersion(),0L)+1);state.setCalculationMethod("WEIGHTED_BKT_ELO");state.setAlgorithmVersion("weighted_bkt_elo_v1");state.setLastInteractionSeq(i.getInteractionSeq());state.setLastInteractionId(i.getId());changed=true;}return new KnowledgeUpdateResult(List.of(state),changed);}
 @Override public StudentKnowledgeState recalibrate(StudentKnowledgeState initial,List<ValidatedInteraction> fullHistory){StudentKnowledgeState clean=copy(initial);clean.setMasteryValue(new BigDecimal("0.30"));clean.setConfidence(BigDecimal.ZERO);clean.setEvidenceCount(0);clean.setAttemptCount(0);clean.setCorrectCount(0);clean.setLastInteractionSeq(0L);return update(clean,fullHistory).getStates().get(0);}
 private StudentKnowledgeState copy(StudentKnowledgeState s){StudentKnowledgeState n=new StudentKnowledgeState();if(s!=null){n.setId(s.getId());n.setUserId(s.getUserId());n.setCourseId(s.getCourseId());n.setKnowledgePointId(s.getKnowledgePointId());n.setMasteryValue(s.getMasteryValue());n.setConfidence(s.getConfidence());n.setEvidenceCount(s.getEvidenceCount());n.setAttemptCount(s.getAttemptCount());n.setCorrectCount(s.getCorrectCount());n.setStateVersion(s.getStateVersion());n.setLastInteractionSeq(s.getLastInteractionSeq());}return n;}
 private BigDecimal clamp(BigDecimal v){return v.max(BigDecimal.ZERO).min(BigDecimal.ONE);}private BigDecimal or(BigDecimal v,BigDecimal d){return v==null?d:v;}private String level(BigDecimal v){return v.compareTo(new BigDecimal("0.8"))>=0?"mastered":v.compareTo(new BigDecimal("0.5"))>=0?"basic":"weak";}
}
